using System;
using NUnit.Framework;

namespace Bar
{
    public class Bar
    {
        [Test]
        public void DoSomeElse(string a)
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void DoSomeForBar(Foo foo)
        {
            Assert.Fail("autogenerated");
        }
    }
}