using System;
using NUnit.Framework;

namespace Foo
{
    public class Foo
    {
        [Test]
        public void DoSomeForFoo()
        {
            Assert.Fail("autogenerated");
        }
    }
}