using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;

namespace TestedClass
{
    public class TestedClass
    {
        [Test]
        public void DoSome(int a)
        {
            Assert.Fail("autogenerated");
        }
    }
}